"""
CLI entry point for fitting a single component.

Usage:
    run-fit-component \\
        --spec-id  <md5-hex> \\
        --manifest <path/to/manifest.json> \\
        --data-path <path/to/data.parquet> \\
        --output-dir <dir>
        [--fold-assignments <path/to/fold_assignments.parquet>]
        [--overwrite]

Loads the spec from the JSON manifest (keyed by component_id MD5 hex), loads
the data parquet, calls fit_one_component, and saves the result via
cache.save_result.  Skips gracefully if the result already exists unless
--overwrite is passed.

When spec['fold_tag'] is not 'is', --fold-assignments must point to the parquet
written by orchestrate.py. The fold_tag encodes the held-out fold as
's{seed}_f{fold}', and the corresponding training rows (where the seed column
!= fold) are passed to fit_one_component.

The manifest is written by orchestrate.py before any jobs are submitted.
"""

from __future__ import annotations

import json
import logging

import click
import pandas as pd

from idd_tc_mortality.cache import component_id, result_exists, save_result
from idd_tc_mortality.fit.fit_component import fit_one_component

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


@click.command()
@click.option(
    "--spec-id",
    required=True,
    help="Component ID (MD5 hex string) to fit. Must exist as a key in the manifest.",
)
@click.option(
    "--manifest",
    "manifest_path",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to JSON manifest written by orchestrate.py. "
         "Keys are component IDs; values are spec dicts.",
)
@click.option(
    "--data-path",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to cleaned training data parquet file.",
)
@click.option(
    "--output-dir",
    required=True,
    type=click.Path(file_okay=False),
    help="Directory where fitted results are written.",
)
@click.option(
    "--fold-assignments",
    "fold_assignments_path",
    default=None,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to fold_assignments.parquet written by orchestrate.py. "
         "Required when spec fold_tag is not 'is'.",
)
@click.option(
    "--overwrite",
    is_flag=True,
    default=False,
    help="Overwrite an existing result if one already exists for this spec-id.",
)
def main(
    spec_id: str,
    manifest_path: str,
    data_path: str,
    output_dir: str,
    fold_assignments_path: str | None,
    overwrite: bool,
) -> None:
    """Fit a single model component and save the result to output-dir."""
    if result_exists(spec_id, output_dir) and not overwrite:
        click.echo(f"Result already exists for {spec_id} — skipping.")
        return

    with open(manifest_path) as f:
        manifest = json.load(f)

    if spec_id not in manifest:
        raise click.UsageError(
            f"spec_id {spec_id!r} not found in manifest {manifest_path!r}. "
            "Check that the manifest was generated by orchestrate.py for this run."
        )

    spec = manifest[spec_id]

    # Verify that the manifest's own component_id hash matches the key.
    # This guards against a manifest with edited spec dicts or stale keys.
    expected_id = component_id(spec)
    if expected_id != spec_id:
        raise click.UsageError(
            f"Manifest key {spec_id!r} does not match the hash of its spec dict "
            f"({expected_id!r}). The manifest may be corrupt or edited."
        )

    logger.info("Fitting component %s (%s/%s)", spec_id, spec["component"], spec.get("family"))

    df = pd.read_parquet(data_path)

    fold_tag = spec.get("fold_tag", "is")
    if fold_tag != "is":
        if fold_assignments_path is None:
            raise click.UsageError(
                f"spec fold_tag={fold_tag!r} requires --fold-assignments."
            )
        # fold_tag format: "s{seed}_f{fold}"
        try:
            seed_part, fold_part = fold_tag.split("_")
            seed_idx = int(seed_part[1:])
            held_out_fold = int(fold_part[1:])
        except (ValueError, IndexError) as exc:
            raise click.UsageError(
                f"Cannot parse fold_tag {fold_tag!r}. "
                "Expected format: 's{{seed}}_f{{fold}}' (e.g. 's0_f2')."
            ) from exc

        fold_df = pd.read_parquet(fold_assignments_path)
        col = f"seed_{seed_idx}"
        if col not in fold_df.columns:
            raise click.UsageError(
                f"Column {col!r} not found in fold assignments file. "
                f"Available columns: {list(fold_df.columns)}"
            )
        train_mask = fold_df[col].values != held_out_fold
        df = df.loc[df.index[train_mask]].copy()
        logger.info(
            "OOS fold_tag=%s: using %d of %d rows for training.",
            fold_tag, int(train_mask.sum()), len(train_mask),
        )

    result = fit_one_component(spec, df)
    if not result.converged:
        logger.warning(
            "Component %s (%s/%s) did not converge: %s",
            spec_id,
            spec["component"],
            spec.get("family"),
            result.meta.get("fit_error", "no error message"),
        )

    save_result(result, spec, output_dir, overwrite=overwrite)
    logger.info(
        "Saved result for %s — converged=%s, n_obs=%d",
        spec_id,
        result.converged,
        len(result.fitted_values),
    )
