"""
CLI entry point for fitting a bundle of components.

Usage:
    run-fit-component \\
        --bundle-file <path/to/bundle_NNNN.json> \\
        --manifest    <path/to/manifest.json> \\
        --data-path   <path/to/data.parquet> \\
        --output-dir  <dir> \\
        [--fold-assignments <path/to/fold_assignments.parquet>]
        [--overwrite]

The bundle file is a JSON list of component_id (MD5 hex) strings written by
orchestrate.py. The worker loads data and manifest once, then iterates over
the spec list — skipping any spec whose result already exists unless --overwrite
is passed.

Fold subsetting is done per-spec: the fold_tag encoded in the manifest spec
governs which rows are withheld, using the fold_assignments parquet written
by orchestrate.py.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import click
import pandas as pd

from idd_tc_mortality.cache import component_id, result_exists, save_result
from idd_tc_mortality.fit.fit_component import fit_one_component

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def _subset_for_fold(
    spec: dict,
    df: pd.DataFrame,
    fold_df: pd.DataFrame | None,
    fold_assignments_path: str | None,
) -> pd.DataFrame:
    """Return the training subset of df for this spec's fold_tag."""
    fold_tag = spec.get("fold_tag", "is")
    if fold_tag == "is" or fold_df is None:
        return df
    if fold_assignments_path is None:
        raise click.UsageError(
            f"spec fold_tag={fold_tag!r} requires --fold-assignments."
        )
    try:
        seed_part, fold_part = fold_tag.split("_")
        seed_idx = int(seed_part[1:])
        held_out_fold = int(fold_part[1:])
    except (ValueError, IndexError) as exc:
        raise click.UsageError(
            f"Cannot parse fold_tag {fold_tag!r}. "
            "Expected format: 's{{seed}}_f{{fold}}' (e.g. 's0_f2')."
        ) from exc
    col = f"seed_{seed_idx}"
    if col not in fold_df.columns:
        raise click.UsageError(
            f"Column {col!r} not found in fold assignments file. "
            f"Available columns: {list(fold_df.columns)}"
        )
    train_mask = fold_df[col].values != held_out_fold
    return df.loc[df.index[train_mask]].copy()


@click.command()
@click.option(
    "--bundle-file",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to a JSON file containing a list of component_id strings to fit.",
)
@click.option(
    "--manifest",
    "manifest_path",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to JSON manifest written by orchestrate.py. "
         "Keys are component IDs; values are spec dicts.",
)
@click.option(
    "--data-path",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to cleaned training data parquet file.",
)
@click.option(
    "--output-dir",
    required=True,
    type=click.Path(file_okay=False),
    help="Directory where fitted results are written.",
)
@click.option(
    "--fold-assignments",
    "fold_assignments_path",
    default=None,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to fold_assignments.parquet written by orchestrate.py. "
         "Required when any spec in the bundle has fold_tag != 'is'.",
)
@click.option(
    "--overwrite",
    is_flag=True,
    default=False,
    help="Overwrite existing results for specs in this bundle.",
)
def main(
    bundle_file: str,
    manifest_path: str,
    data_path: str,
    output_dir: str,
    fold_assignments_path: str | None,
    overwrite: bool,
) -> None:
    """Fit a bundle of model components and save results to output-dir."""
    with open(bundle_file) as f:
        spec_ids: list[str] = json.load(f)

    with open(manifest_path) as f:
        manifest: dict = json.load(f)

    df = pd.read_parquet(data_path)
    fold_df = pd.read_parquet(fold_assignments_path) if fold_assignments_path else None

    n = len(spec_ids)
    for i, spec_id in enumerate(spec_ids, 1):
        if result_exists(spec_id, output_dir) and not overwrite:
            logger.info("[%d/%d] Skipping %s — already done.", i, n, spec_id)
            continue

        if spec_id not in manifest:
            raise RuntimeError(
                f"spec_id {spec_id!r} not found in manifest {manifest_path!r}. "
                "Check that the manifest was generated by orchestrate.py for this run."
            )

        spec = manifest[spec_id]

        expected_id = component_id(spec)
        if expected_id != spec_id:
            raise RuntimeError(
                f"Manifest key {spec_id!r} does not match the hash of its spec dict "
                f"({expected_id!r}). The manifest may be corrupt or edited."
            )

        df_train = _subset_for_fold(spec, df, fold_df, fold_assignments_path)
        logger.info(
            "[%d/%d] Fitting %s (%s/%s)", i, n, spec_id,
            spec["component"], spec.get("family"),
        )

        result = fit_one_component(spec, df_train)
        if not result.converged:
            logger.warning(
                "Component %s (%s/%s) did not converge: %s",
                spec_id, spec["component"], spec.get("family"),
                result.meta.get("fit_error", "no error message"),
            )

        save_result(result, spec, output_dir, overwrite=overwrite)
        logger.info(
            "[%d/%d] Saved %s — converged=%s, n_obs=%d",
            i, n, spec_id, result.converged, len(result.fitted_values),
        )
